# Restricted Boltsmann Machine
### Sistema de recomendação de filmes

In [1]:
from rbm import RBM
import numpy as np

In [8]:
# Instanciando um objeto RBM
rbm = RBM(num_visible = 6, num_hidden = 2)

In [9]:
# valores 1 segnifica que o filme foi assistido e 0 que não foi assistido
# a cada linha significa que temos 6 pessoas que assistiram ao filme
base = np.array([[1,1,1,0,0,0],
                 [1,0,1,0,0,0],
                 [1,1,1,0,0,0],
                 [0,0,1,1,1,1],
                 [0,0,1,1,0,1],
                 [0,0,1,1,0,1]])

In [10]:
# Lista dos filmes
filmes = ["A bruxa", "Invocação do mal", "O chamado",
          "Se beber não case", "Gente grande", "American pie"]

## Treinamento da RBM

In [13]:
rbm.train(base, max_epochs = 5000)

Epoch 0: error is 9.033262449736895
Epoch 1: error is 8.951423359143986
Epoch 2: error is 8.772236465286442
Epoch 3: error is 8.593538625833874
Epoch 4: error is 8.445434557147703
Epoch 5: error is 8.350961898150452
Epoch 6: error is 8.270169628837728
Epoch 7: error is 8.124966836126665
Epoch 8: error is 8.030555532807377
Epoch 9: error is 7.840329168460806
Epoch 10: error is 7.7040681343838395
Epoch 11: error is 7.635115802282926
Epoch 12: error is 7.643178306950068
Epoch 13: error is 7.569355274345297
Epoch 14: error is 7.498903395045732
Epoch 15: error is 7.420439675907159
Epoch 16: error is 7.4197808364861135
Epoch 17: error is 7.661976232805901
Epoch 18: error is 7.601574970695637
Epoch 19: error is 7.366225287306606
Epoch 20: error is 7.187290508117757
Epoch 21: error is 7.27871722665416
Epoch 22: error is 7.295040047440649
Epoch 23: error is 7.0327988195739755
Epoch 24: error is 7.17948991965054
Epoch 25: error is 7.095060824441636
Epoch 26: error is 7.273690853459273
Epoch 27: 

Epoch 446: error is 1.5657833976750795
Epoch 447: error is 1.9731174204932092
Epoch 448: error is 1.9604765732854155
Epoch 449: error is 1.270182653282046
Epoch 450: error is 1.9438831331772637
Epoch 451: error is 1.2588403394021221
Epoch 452: error is 1.9014882744792128
Epoch 453: error is 1.554667305296161
Epoch 454: error is 2.2377048376624025
Epoch 455: error is 1.5504295311252017
Epoch 456: error is 1.2500568047258958
Epoch 457: error is 1.8879302874958312
Epoch 458: error is 1.5415727136737862
Epoch 459: error is 1.2464954346867876
Epoch 460: error is 1.537799904120547
Epoch 461: error is 1.5352034333801774
Epoch 462: error is 1.241726325525995
Epoch 463: error is 1.2376762534910397
Epoch 464: error is 1.530641733829002
Epoch 465: error is 1.233429134579653
Epoch 466: error is 1.5272062447751675
Epoch 467: error is 1.5247740931564118
Epoch 468: error is 1.5224034973453269
Epoch 469: error is 1.5200924617823475
Epoch 470: error is 1.5178390518101255
Epoch 471: error is 1.515641392

Epoch 696: error is 1.3808249635397651
Epoch 697: error is 1.3803373784905377
Epoch 698: error is 1.07049533502485
Epoch 699: error is 1.380572587853972
Epoch 700: error is 1.0667981877639554
Epoch 701: error is 1.3808108961329657
Epoch 702: error is 1.380294257809826
Epoch 703: error is 1.3797935235781595
Epoch 704: error is 1.0656033161307912
Epoch 705: error is 1.380042922774137
Epoch 706: error is 1.3795355628689394
Epoch 707: error is 1.3790438606099664
Epoch 708: error is 1.37856727513543
Epoch 709: error is 1.3781052812189079
Epoch 710: error is 1.0667048729319661
Epoch 711: error is 1.3783715580582272
Epoch 712: error is 1.0629771540420043
Epoch 713: error is 1.3786416211659218
Epoch 714: error is 1.3781488834319202
Epoch 715: error is 1.3776714439059414
Epoch 716: error is 1.3772087722541142
Epoch 717: error is 1.3767603535778061
Epoch 718: error is 1.0640685750445291
Epoch 719: error is 1.3770455416979424
Epoch 720: error is 1.3765880880678438
Epoch 721: error is 1.3761447779

Epoch 932: error is 1.3594434427635753
Epoch 933: error is 1.3590399810938802
Epoch 934: error is 1.3586508756406002
Epoch 935: error is 0.9989328304467384
Epoch 936: error is 0.9943241249589766
Epoch 937: error is 1.3601971191203592
Epoch 938: error is 1.3597555009759563
Epoch 939: error is 1.3593295732710298
Epoch 940: error is 0.9939050504130527
Epoch 941: error is 1.3598968595227061
Epoch 942: error is 1.3594604278076792
Epoch 943: error is 1.3590395238057649
Epoch 944: error is 1.3586336183268728
Epoch 945: error is 1.3582421962188815
Epoch 946: error is 2.272344704613348
Epoch 947: error is 1.358815076503652
Epoch 948: error is 1.3584115776807109
Epoch 949: error is 1.3580224937040848
Epoch 950: error is 1.3576473253466934
Epoch 951: error is 1.3572855871991478
Epoch 952: error is 1.3569368075388961
Epoch 953: error is 0.9991872143349222
Epoch 954: error is 1.3575116939290055
Epoch 955: error is 1.3571490300308824
Epoch 956: error is 1.356799373666305
Epoch 957: error is 1.356462

Epoch 1179: error is 0.9786988937691656
Epoch 1180: error is 0.9736870872467217
Epoch 1181: error is 1.3503758792919767
Epoch 1182: error is 1.3500722908342615
Epoch 1183: error is 1.3497803127802395
Epoch 1184: error is 1.3494995308643034
Epoch 1185: error is 1.3492295432021082
Epoch 1186: error is 1.3489699600955583
Epoch 1187: error is 1.3487204038275313
Epoch 1188: error is 0.9766852976034417
Epoch 1189: error is 1.3493714816006195
Epoch 1190: error is 1.3491037868428188
Epoch 1191: error is 1.348846422021136
Epoch 1192: error is 0.9749966430331409
Epoch 1193: error is 1.349502181124199
Epoch 1194: error is 0.9711751075268041
Epoch 1195: error is 1.3501691027581875
Epoch 1196: error is 1.3498657617233205
Epoch 1197: error is 0.9686691690179356
Epoch 1198: error is 1.3505381429916223
Epoch 1199: error is 0.9651001097364098
Epoch 1200: error is 1.3512165245779506
Epoch 1201: error is 1.3508686739762736
Epoch 1202: error is 1.3505340201102063
Epoch 1203: error is 1.350212103587361
Epo

Epoch 1417: error is 1.353396586643519
Epoch 1418: error is 0.9112475451482186
Epoch 1419: error is 1.3541055924876202
Epoch 1420: error is 1.3535658901157441
Epoch 1421: error is 1.3530458559697334
Epoch 1422: error is 1.352544882854668
Epoch 1423: error is 1.352062375836949
Epoch 1424: error is 0.9143366930266391
Epoch 1425: error is 1.3527853301487096
Epoch 1426: error is 0.9117523521861061
Epoch 1427: error is 1.3535018895455486
Epoch 1428: error is 1.3529826391801525
Epoch 1429: error is 1.3524824308276455
Epoch 1430: error is 1.3520006701785918
Epoch 1431: error is 1.3515367753956395
Epoch 1432: error is 1.3510901772859263
Epoch 1433: error is 1.3506603194346174
Epoch 1434: error is 1.350246658302052
Epoch 1435: error is 1.3498486632869227
Epoch 1436: error is 1.3494658167578055
Epoch 1437: error is 0.9211099069504165
Epoch 1438: error is 1.3502021221994012
Epoch 1439: error is 1.3498051091560876
Epoch 1440: error is 1.3494232187462898
Epoch 1441: error is 0.9206584138888256
Epoc

Epoch 1655: error is 1.3555661118142395
Epoch 1656: error is 0.8722624862375207
Epoch 1657: error is 0.8688581778340756
Epoch 1658: error is 1.3576275800719362
Epoch 1659: error is 0.8670764247118806
Epoch 1660: error is 1.3582961430085474
Epoch 1661: error is 1.3575733924803774
Epoch 1662: error is 1.3568757944279624
Epoch 1663: error is 1.3562026649621919
Epoch 1664: error is 1.3555533282913772
Epoch 1665: error is 1.3549271173904744
Epoch 1666: error is 0.8727732693370468
Epoch 1667: error is 1.3556438256796892
Epoch 1668: error is 0.8707895247070495
Epoch 1669: error is 1.3563493911974873
Epoch 1670: error is 1.3556949822924547
Epoch 1671: error is 1.3550638569424578
Epoch 1672: error is 0.8718073353537797
Epoch 1673: error is 1.3557794784512847
Epoch 1674: error is 0.8698388322905212
Epoch 1675: error is 0.8664568232759854
Epoch 1676: error is 0.8631834012013043
Epoch 1677: error is 0.8600143887394769
Epoch 1678: error is 1.360636514021033
Epoch 1679: error is 1.359833794282488
Ep

Epoch 1872: error is 0.8055274525832418
Epoch 1873: error is 0.8035754166130451
Epoch 1874: error is 1.3841964541374647
Epoch 1875: error is 1.3827113250522491
Epoch 1876: error is 1.3812668215019486
Epoch 1877: error is 0.8067340187433152
Epoch 1878: error is 0.8047323447786748
Epoch 1879: error is 1.3829139704457196
Epoch 1880: error is 1.381464657901188
Epoch 1881: error is 0.8061606289734898
Epoch 1882: error is 0.8041662318864792
Epoch 1883: error is 0.802230051374568
Epoch 1884: error is 1.3846298140713946
Epoch 1885: error is 1.3831348312843728
Epoch 1886: error is 1.381680601032792
Epoch 1887: error is 1.3802666393090521
Epoch 1888: error is 1.378892432563017
Epoch 1889: error is 0.8087802115133835
Epoch 1890: error is 0.8066849955996043
Epoch 1891: error is 0.8046516440642869
Epoch 1892: error is 1.3821477384851757
Epoch 1893: error is 0.8043653639287209
Epoch 1894: error is 1.3822511299659177
Epoch 1895: error is 0.804082980362558
Epoch 1896: error is 0.8021165551756279
Epoch

Epoch 2256: error is 0.7322750817474848
Epoch 2257: error is 1.4485912988916942
Epoch 2258: error is 0.732971787052886
Epoch 2259: error is 0.7323761023622726
Epoch 2260: error is 0.7317934771937499
Epoch 2261: error is 0.73122354890778
Epoch 2262: error is 0.7306659668387528
Epoch 2263: error is 0.7301203918388637
Epoch 2264: error is 0.7295864958414257
Epoch 2265: error is 0.7290639614427129
Epoch 2266: error is 0.7285524815014823
Epoch 2267: error is 1.4556744658106897
Epoch 2268: error is 0.729250994231736
Epoch 2269: error is 0.7287324779876249
Epoch 2270: error is 1.4550531062819256
Epoch 2271: error is 0.7294320157026197
Epoch 2272: error is 1.6417442413615562
Epoch 2273: error is 1.4581931794615945
Epoch 2274: error is 0.727909989170739
Epoch 2275: error is 0.7274166296557307
Epoch 2276: error is 1.4575002023234056
Epoch 2277: error is 0.7281151801232096
Epoch 2278: error is 1.4558004104163451
Epoch 2279: error is 0.7288157297612408
Epoch 2280: error is 0.7282972500504656
Epoch

Epoch 2495: error is 1.5083903283526139
Epoch 2496: error is 0.7046104003478739
Epoch 2497: error is 1.5060485575667224
Epoch 2498: error is 0.7051383629110073
Epoch 2499: error is 1.5037269964033184
Epoch 2500: error is 0.7056828599940209
Epoch 2501: error is 1.5014267488037143
Epoch 2502: error is 1.6181444964676057
Epoch 2503: error is 0.7051281984381209
Epoch 2504: error is 0.7049508426125115
Epoch 2505: error is 0.7047762266897581
Epoch 2506: error is 1.5045021466097355
Epoch 2507: error is 0.7053170660417549
Epoch 2508: error is 1.5021967971259405
Epoch 2509: error is 0.7058738814451756
Epoch 2510: error is 0.7056799531936814
Epoch 2511: error is 1.500552241159356
Epoch 2512: error is 2.4107253461517315
Epoch 2513: error is 0.7060458688054776
Epoch 2514: error is 0.7058468285957636
Epoch 2515: error is 0.7056509852761155
Epoch 2516: error is 0.7054582712306688
Epoch 2517: error is 0.7052686205422194
Epoch 2518: error is 1.5015013793069483
Epoch 2519: error is 0.7058322487398587
E

Epoch 2868: error is 0.6910860518966806
Epoch 2869: error is 0.6910165654783901
Epoch 2870: error is 0.6909478609940191
Epoch 2871: error is 0.6908799259041837
Epoch 2872: error is 0.6908127479052153
Epoch 2873: error is 0.6907463149240081
Epoch 2874: error is 0.6906806151129952
Epoch 2875: error is 0.6906156368452521
Epoch 2876: error is 0.690551368709725
Epoch 2877: error is 0.6904877995065741
Epoch 2878: error is 1.5426150724129695
Epoch 2879: error is 0.6908217101608262
Epoch 2880: error is 0.6907535495943935
Epoch 2881: error is 2.4568619840383197
Epoch 2882: error is 0.6906195024687015
Epoch 2883: error is 0.6905535918273372
Epoch 2884: error is 0.6904884074526803
Epoch 2885: error is 0.6904239378570743
Epoch 2886: error is 0.6903601717656476
Epoch 2887: error is 0.6902970981117321
Epoch 2888: error is 0.6902347060324007
Epoch 2889: error is 1.543275093640544
Epoch 2890: error is 0.6905655706606059
Epoch 2891: error is 1.54089961633
Epoch 2892: error is 0.6909159322360381
Epoch 2

Epoch 3083: error is 0.6869816054318587
Epoch 3084: error is 0.686928086572506
Epoch 3085: error is 1.5497105498032047
Epoch 3086: error is 0.6872440477186403
Epoch 3087: error is 1.5473796836502
Epoch 3088: error is 0.6875781326137067
Epoch 3089: error is 0.6875157469831922
Epoch 3090: error is 0.6874540522390991
Epoch 3091: error is 0.6873930377626748
Epoch 3092: error is 0.6873326931279384
Epoch 3093: error is 0.6872730080975736
Epoch 3094: error is 0.6872139726189235
Epoch 3095: error is 1.5470345965723546
Epoch 3096: error is 1.5443553956476184
Epoch 3097: error is 0.6879739920717689
Epoch 3098: error is 0.6879047216048508
Epoch 3099: error is 0.6878362502203295
Epoch 3100: error is 0.6877685653212344
Epoch 3101: error is 0.687701654546182
Epoch 3102: error is 0.6876355057641891
Epoch 3103: error is 0.6875701070696182
Epoch 3104: error is 0.6875054467772522
Epoch 3105: error is 1.6156201678191664
Epoch 3106: error is 0.6869283525148848
Epoch 3107: error is 0.6868719207048471
Epoch

Epoch 3322: error is 0.683044871937614
Epoch 3323: error is 1.5629116928021098
Epoch 3324: error is 0.6832963202638039
Epoch 3325: error is 0.6832577108219438
Epoch 3326: error is 0.68321945833904
Epoch 3327: error is 0.6831815580347804
Epoch 3328: error is 0.6831440052039793
Epoch 3329: error is 0.6831067952152003
Epoch 3330: error is 0.6830699235094081
Epoch 3331: error is 0.6830333855986507
Epoch 3332: error is 0.6829971770647665
Epoch 3333: error is 0.68296129355812
Epoch 3334: error is 0.6829257307963669
Epoch 3335: error is 0.6828904845632403
Epoch 3336: error is 0.6828555507073649
Epoch 3337: error is 1.5635649350073648
Epoch 3338: error is 0.6831040615242545
Epoch 3339: error is 0.6830662481008565
Epoch 3340: error is 0.6830287815707886
Epoch 3341: error is 0.6829916573185558
Epoch 3342: error is 0.6829548708007371
Epoch 3343: error is 0.6829184175446723
Epoch 3344: error is 1.5625474175426837
Epoch 3345: error is 0.6831754548199255
Epoch 3346: error is 0.6831360296719847
Epoch

Epoch 3564: error is 0.6812060933891172
Epoch 3565: error is 0.6811696023302678
Epoch 3566: error is 0.6811334484482989
Epoch 3567: error is 0.6810976273788997
Epoch 3568: error is 0.6810621348247776
Epoch 3569: error is 0.681026966554443
Epoch 3570: error is 0.6809921184010216
Epoch 3571: error is 0.6809575862610917
Epoch 3572: error is 0.6809233660935452
Epoch 3573: error is 0.6808894539184736
Epoch 3574: error is 0.680855845816076
Epoch 3575: error is 0.6808225379255906
Epoch 3576: error is 0.6807895264442486
Epoch 3577: error is 0.6807568076262498
Epoch 3578: error is 0.6807243777817581
Epoch 3579: error is 0.6806922332759188
Epoch 3580: error is 0.6806603705278962
Epoch 3581: error is 0.6806287860099307
Epoch 3582: error is 1.6195541420328587
Epoch 3583: error is 0.6802852053525148
Epoch 3584: error is 0.6802575306392159
Epoch 3585: error is 0.6802300823191686
Epoch 3586: error is 0.6802028576618916
Epoch 3587: error is 0.6801758539755622
Epoch 3588: error is 0.6801490686063794
Ep

Epoch 3934: error is 0.6762439372753485
Epoch 3935: error is 0.6762355151385513
Epoch 3936: error is 0.6762271215640366
Epoch 3937: error is 0.6762187563164522
Epoch 3938: error is 0.6762104191629021
Epoch 3939: error is 1.5993190961175148
Epoch 3940: error is 0.6762755031306759
Epoch 3941: error is 0.6762665149685306
Epoch 3942: error is 0.6762575609385022
Epoch 3943: error is 0.6762486407534163
Epoch 3944: error is 1.5977805198807977
Epoch 3945: error is 0.6763254148719823
Epoch 3946: error is 0.6763157456382212
Epoch 3947: error is 0.6763061172103416
Epoch 3948: error is 0.6762965292360587
Epoch 3949: error is 0.6762869813666635
Epoch 3950: error is 1.596330807654728
Epoch 3951: error is 0.6763746945486401
Epoch 3952: error is 0.6763643054236216
Epoch 3953: error is 0.6763539642449055
Epoch 3954: error is 0.6763436705882226
Epoch 3955: error is 0.6763334240336719
Epoch 3956: error is 0.6763232241656683
Epoch 3957: error is 0.6763130705728942
Epoch 3958: error is 0.6763029628482519
E

Epoch 4148: error is 0.6752006648187074
Epoch 4149: error is 0.6751926091564456
Epoch 4150: error is 0.675184585946115
Epoch 4151: error is 0.6751765949194305
Epoch 4152: error is 0.6751686358107348
Epoch 4153: error is 0.6751607083569696
Epoch 4154: error is 0.6751528122976471
Epoch 4155: error is 0.6751449473748222
Epoch 4156: error is 0.6751371133330667
Epoch 4157: error is 0.6751293099194396
Epoch 4158: error is 0.6751215368834625
Epoch 4159: error is 0.6751137939770928
Epoch 4160: error is 0.6751060809546968
Epoch 4161: error is 0.6750983975730243
Epoch 4162: error is 0.6750907435911839
Epoch 4163: error is 0.6750831187706167
Epoch 4164: error is 1.6013503405184764
Epoch 4165: error is 0.6751582932737584
Epoch 4166: error is 0.6751499970962962
Epoch 4167: error is 0.6751417358821331
Epoch 4168: error is 0.6751335093423466
Epoch 4169: error is 0.6751253171907885
Epoch 4170: error is 0.675117159144056
Epoch 4171: error is 0.6751090349214627
Epoch 4172: error is 0.6751009442450108
Ep

Epoch 4377: error is 0.6742269493228634
Epoch 4378: error is 0.6742197288668065
Epoch 4379: error is 0.6742125384600105
Epoch 4380: error is 0.6742053778686478
Epoch 4381: error is 0.6741982468609536
Epoch 4382: error is 0.674191145207207
Epoch 4383: error is 0.6741840726797125
Epoch 4384: error is 0.6741770290527782
Epoch 4385: error is 0.6741700141026983
Epoch 4386: error is 0.6741630276077341
Epoch 4387: error is 0.6741560693480945
Epoch 4388: error is 0.6741491391059181
Epoch 4389: error is 0.6741422366652555
Epoch 4390: error is 0.6741353618120497
Epoch 4391: error is 0.6741285143341198
Epoch 4392: error is 0.674121694021142
Epoch 4393: error is 0.6741149006646332
Epoch 4394: error is 0.6741081340579342
Epoch 4395: error is 0.6741013939961906
Epoch 4396: error is 0.6740946802763381
Epoch 4397: error is 1.604157472667663
Epoch 4398: error is 0.6741708902464486
Epoch 4399: error is 0.6741635507221483
Epoch 4400: error is 0.6741562426332192
Epoch 4401: error is 0.6741489657338123
Epo

Epoch 4617: error is 0.673461749995602
Epoch 4618: error is 0.6734547213537669
Epoch 4619: error is 0.6734477247845108
Epoch 4620: error is 0.673440760040037
Epoch 4621: error is 1.604146852098599
Epoch 4622: error is 0.6735304933834708
Epoch 4623: error is 0.6735228433245921
Epoch 4624: error is 2.5546141718323705
Epoch 4625: error is 0.6735076545295593
Epoch 4626: error is 0.6735001152094626
Epoch 4627: error is 0.6734926122227006
Epoch 4628: error is 0.6734851452837883
Epoch 4629: error is 0.6734777141097872
Epoch 4630: error is 0.6734703184202779
Epoch 4631: error is 0.6734629579373388
Epoch 4632: error is 0.6734556323855161
Epoch 4633: error is 0.6734483414918013
Epoch 4634: error is 0.6734410849856068
Epoch 4635: error is 0.6734338625987412
Epoch 4636: error is 1.6035850412763097
Epoch 4637: error is 0.6735275128011915
Epoch 4638: error is 0.6735195775301676
Epoch 4639: error is 0.6735116819961314
Epoch 4640: error is 0.6735038258827493
Epoch 4641: error is 0.6734960088765571
Epo

# Análise dos Weights (pesos dos neurônios)
Analizando os Weights podemos ver que o neurônio zero se especializou em filmes de comédia e o neurônio 1 em filmes de terror

In [19]:
rbm.weights

array([[ 2.46366449,  2.3312096 ,  0.3569082 ],
       [-0.99970294, -3.32434016,  7.89991667],
       [ 0.25235974, -7.20856101,  3.35850361],
       [ 4.95643721,  3.91452638,  1.86910399],
       [ 0.91108094,  3.65246715, -8.21536996],
       [-1.32619399,  0.62094651, -4.54356535],
       [ 0.91634649,  3.6484421 , -8.21797779]])

## Teste de recomendação de filmes para usuários

In [20]:
usuario1 = np.array([[1,1,0,1,0,0]])
usuario2 = np.array([[0,0,0,1,1,0]])

## Verificando qual dos neurônios foi ativado


Para esse primeiro usuário o neurônio 1 que se especializou em filmes de comédia foi ativado, logo isso significa que esse usuário pode gostar mais de filmes de comédia do que de terror, dessa forma, podemos recomendar mais filmes de comédia para esse usuário.

In [22]:
rbm.run_visible(usuario1)

array([[0., 1.]])

Para esse segundo usuário que se ativou foi o neurônio 0 que se especializou em filmes de terror, logo podemos deduzir que esse usuário pode gostar mais de filmes de terror, assim, podemos recomendar mais filmes desse gênero.

In [18]:
rbm.run_visible(usuario2)

array([[1., 0.]])

### Recomendando filmes para os usuário analisados anteriormente

### Recomendação de filmes para o Usuário 1

In [57]:
camada_escondida = rbm.run_visible(usuario1)
recomendacao = rbm.run_hidden(camada_escondida)
print(recomendacao)

[[1. 1. 1. 0. 0. 0.]]


In [58]:
print("\n")
print("Filmes Recomendados para o Usuário 1")
print("\n")

for i in range(len(usuario1[0])):
    #print(usuario1[0,i])
    if usuario1[0,i] == 0 and recomendacao[0,i] == 1:
        print(filmes[i])
print("\n")



Filmes Recomendados para o Usuário 1


O chamado




## Recomendação de filmes para o Usuário 2

In [50]:
camada_escondida2 = rbm.run_visible(usuario2)
recomendacao2 = rbm.run_hidden(camada_escondida2)
print(recomendacao)

[[1. 1. 1. 0. 0. 0.]]


In [51]:
print("\n")
print("Filmes Recomendados para o Usuário 2")
print("\n")
for i in range(len(usuario2[0])):
    #print(usuario1[0,i])
    if usuario2[0,i] == 0 and recomendacao2[0,i] == 1:
        print(filmes[i])

print("")



Filmes Recomendados para o Usuário 2


O chamado
American pie

